### ISSUE TITLE
There is seems something  wrong... or I am wrong...

### ISSUE THREAD

**Issue by joenahm** [KaneCohen/cronus#2]
my code:
```
    var now = new cronus('2018-07-22');
    var date = new cronus('2018-07-07');
    var d = now.diff(date,'M');
    console.log(now,date,d);
```
I expect the `d` is 0, but it is 1 . Why ?

**Comment by KaneCohen** [comment]
@joenahm hi. Final result of the difference calculation is a rounded number which in this case leads to 1 month. For simplicity's sake 1 month internally in the cronus equals to 30 days.

Here's a generalized calculation run internally: `Math.round(NumberOfDaysDiff / 30)`.

I'll look into fixing the issue.

**Comment by KaneCohen** [comment]
Please, check `v0.5.5` - this issue should be resolved there. Months and years should be counted based on calendar dates. Which means that 1 month is a difference between current month day and comparison month day.
